name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Login to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.ARTIFACT_REGISTRY_OPENSOURCE_FORK_GOOGLE_REGISTRY }}
          username: _json_key
          password: ${{ secrets.ARTIFACT_REGISTRY_GOOGLE_OPENSOURCE_FORK_JSON_KEY }}

      - name: Build and push Docker image for back
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ vars.ARTIFACT_REGISTRY_OPENSOURCE_FORK_GOOGLE_REGISTRY }}/${{ vars.ARTIFACT_REGISTRY_OPENSOURCE_FORK_GOOGLE_PROJECT }}/singer-tap-google-ads:${{ github.ref_name }}
          build-args: |
            MAVEN_USERNAME=${{ secrets.MAVEN_USERNAME }}
            MAVEN_PASSWORD=${{ secrets.MAVEN_PASSWORD }}
            MAVEN_URL=${{ vars.MAVEN_URL }}
